name: usgdp-npp-dev
dependencies:
  - python>=3.10.8
  - ipython
  - numpy>=1.23.4
  - scipy>=1.9.3
  - pandas>=1.5.2
  - pandas-datareader>=0.10.0
  - bokeh>=2.4.3, <3.0
  - pytest>=7.1.2
  - coverage>=6.3.1
  - codecov>=2.1.11
  - black>=22.6.0
  - pip>=22.3.1
  - pip:
    - linecheck>=0.1.0
